# Generated by Django 6.0.4 on 2026-04-27 00:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_alter_product_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='variant',
            name='price',
            field=models.IntegerField(),
        ),
    ]
