# Generated by Django 6.0.4 on 2026-04-27 01:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_alter_variant_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='variant',
            name='price',
            field=models.DecimalField(decimal_places=0, max_digits=15),
        ),
    ]
