# Generated by Django 6.0.4 on 2026-04-27 02:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_alter_variant_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='variant',
            name='colour',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='product.colour'),
        ),
        migrations.AlterField(
            model_name='variant',
            name='size',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='product.size'),
        ),
    ]
