# Generated by Django 6.0.4 on 2026-05-23 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_alter_variant_colour_alter_variant_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagep',
            name='order',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
