# Generated by Django 6.0.4 on 2026-05-23 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0006_imagep_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagep',
            name='order',
            field=models.PositiveSmallIntegerField(default=1),
            preserve_default=False,
        ),
    ]
