# Generated by Django 6.0.4 on 2026-09-14 14:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0017_review_rating_range'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='size',
            options={'ordering': ['id']},
        ),
    ]
