# Generated by Django 6.0.4 on 2026-06-20 14:15

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_user_phone_verified'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(error_messages={'unique': "Ushbu raqam allaqachon ro'yxatdan o'tgan."}, max_length=17, unique=True, validators=[django.core.validators.RegexValidator(message='format: +998 XX XXX XX XX', regex='^\\+998 ?\\d{2} ?\\d{3} ?\\d{2} ?\\d{2}$')]),
        ),
    ]
