# Generated by Django 6.0.4 on 2026-05-07 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_msg_phone_num'),
    ]

    operations = [
        migrations.AlterField(
            model_name='Msg',
            name='phone_num',
            field=models.CharField(max_length=25),
        ),
    ]
