# Generated by Django 6.0.4 on 2026-06-22 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_msg_phone_num'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='msg',
            options={'ordering': ['-id']},
        ),
        migrations.AddField(
            model_name='msg',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
