# Generated by Django 6.0.4 on 2026-05-23 17:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0007_alter_imagep_order'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='imagep',
            options={'ordering': ['order', 'id']},
        ),
    ]
