# Generated by Django 6.0.4 on 2026-09-13 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0014_product_fit_two_values'),
    ]

    operations = [
        migrations.AddField(
            model_name='sizechart',
            name='fit',
            field=models.CharField(blank=True, db_index=True, default='', help_text='Shu qolipdagi mahsulotlar uchun standart jadval.', max_length=20),
        ),
    ]
