# Generated by Django 6.0.4 on 2026-09-22 08:06

import product.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0022_imagep_height_imagep_renditions_imagep_width_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Slide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('width', models.PositiveIntegerField(blank=True, editable=False, null=True)),
                ('height', models.PositiveIntegerField(blank=True, editable=False, null=True)),
                ('renditions', models.JSONField(blank=True, default=dict, editable=False)),
                ('picture', models.ImageField(upload_to='slides/')),
                ('link', models.CharField(blank=True, default='', max_length=200, validators=[product.models.slide_link])),
                ('alt', models.CharField(help_text='Oʻzbekcha — asosiy matn', max_length=120)),
                ('alt_ru', models.CharField(blank=True, default='', max_length=120)),
                ('alt_en', models.CharField(blank=True, default='', max_length=120)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'ordering': ['sort_order', 'id'],
            },
        ),
    ]
