"""A slide's second picture: the phone's, 16:9, in a row of its own (§17 #302).

The laptop picture on :class:`Slide` becomes optional, since a slide may now have
either picture, or both. No data to move: a slide made before this keeps its one
picture as the laptop's, and it is shown on both screens exactly as before.
"""
# Generated by Django 6.0.4 on 2026-09-27 23:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0024_product_updated_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="slide",
            name="picture",
            field=models.ImageField(blank=True, upload_to="slides/"),
        ),
        migrations.CreateModel(
            name="SlidePhone",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "width",
                    models.PositiveIntegerField(blank=True, editable=False, null=True),
                ),
                (
                    "height",
                    models.PositiveIntegerField(blank=True, editable=False, null=True),
                ),
                (
                    "renditions",
                    models.JSONField(blank=True, default=dict, editable=False),
                ),
                ("picture", models.ImageField(upload_to="slides/phone/")),
                (
                    "slide",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="phone",
                        to="product.slide",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
