# Generated by Django 6.0.4 on 2026-09-09 18:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0009_alter_order_address'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveryOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, unique=True)),
                ('name', models.CharField(help_text='Oʻzbekcha — asosiy matn', max_length=120)),
                ('name_ru', models.CharField(blank=True, default='', max_length=120)),
                ('name_en', models.CharField(blank=True, default='', max_length=120)),
                ('note', models.TextField(blank=True, default='', help_text='Oʻzbekcha — asosiy matn')),
                ('note_ru', models.TextField(blank=True, default='')),
                ('note_en', models.TextField(blank=True, default='')),
                ('price', models.DecimalField(decimal_places=0, max_digits=15)),
                ('free_from_items', models.PositiveSmallIntegerField(default=0)),
                ('requires_pickup_point', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'ordering': ['sort_order', 'code'],
            },
        ),
        migrations.CreateModel(
            name='PickupPoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, unique=True)),
                ('name', models.CharField(help_text='Oʻzbekcha — asosiy matn', max_length=160)),
                ('name_ru', models.CharField(blank=True, default='', max_length=160)),
                ('name_en', models.CharField(blank=True, default='', max_length=160)),
                ('region', models.CharField(db_index=True, max_length=80)),
                ('district', models.CharField(db_index=True, max_length=80)),
                ('address', models.CharField(help_text='Oʻzbekcha — asosiy matn', max_length=255)),
                ('address_ru', models.CharField(blank=True, default='', max_length=255)),
                ('address_en', models.CharField(blank=True, default='', max_length=255)),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('working_hours', models.CharField(blank=True, default='', max_length=120)),
                ('phone', models.CharField(blank=True, default='', max_length=30)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'ordering': ['region', 'district', 'name'],
            },
        ),
        migrations.AddField(
            model_name='order',
            name='delivery_price',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=15),
        ),
        migrations.AddField(
            model_name='order',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='order_no',
            field=models.CharField(blank=True, db_index=True, max_length=20, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='order',
            name='pickup_snapshot',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='order',
            name='delivery_option',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='payment.deliveryoption'),
        ),
        migrations.AddField(
            model_name='order',
            name='pickup_point',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='payment.pickuppoint'),
        ),
    ]
