# Generated by Django 6.0.4 on 2026-09-22 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0020_alter_order_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('click', 'Click'), ('payme', 'Payme'), ('octo', 'Octo'), ('cash', 'Naqd pul')], default='click', max_length=20),
        ),
    ]
