# Generated by Django 6.0.4 on 2026-05-07 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='Msg',
            name='phone_num',
            field=models.CharField(default=' hj', max_length=25),
        ),
    ]
