# Generated by Django 6.0.4 on 2026-06-22 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_msg_options_msg_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='msg',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
