# Generated by Django 6.0.4 on 2026-09-14 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_msg_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='msg',
            name='is_read',
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
