# Generated by Django 6.0.4 on 2026-04-27 01:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartitem',
            name='price_stat',
            field=models.DecimalField(decimal_places=0, max_digits=15),
        ),
    ]
