# Generated by Django 6.0.4 on 2026-09-14 12:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('payment', '0015_delivery_price_and_payment_options'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderStatusChange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_status', models.CharField(blank=True, default='', max_length=50)),
                ('to_status', models.CharField(max_length=50)),
                ('changed_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('note', models.CharField(blank=True, default='', max_length=200)),
                ('changed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_status_changes', to=settings.AUTH_USER_MODEL)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_changes', to='payment.order')),
            ],
            options={
                'verbose_name': 'Holat oʻzgarishi',
                'verbose_name_plural': 'Holat oʻzgarishlari',
                'ordering': ['-changed_at', '-id'],
                'indexes': [models.Index(fields=['order', '-changed_at'], name='panel_order_order_i_95ce71_idx')],
            },
        ),
    ]
