# Generated by Django 6.0.4 on 2026-04-29 20:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0002_address_order_updated_at'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Address',
        ),
    ]
