# Generated by Django 6.0.4 on 2026-05-06 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0003_delete_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('paying', "To'lanmoqda"), ('paid', "To'langan"), ('processing', 'Jarayonda'), ('on_the_way', "Yo'lda"), ('done', 'Bajarildi'), ('cancelled', 'Bekor qilindi')], db_index=True, default='active', max_length=50),
        ),
    ]
