# Generated by Django 6.0.4 on 2026-06-09 14:03

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0005_order_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='phone',
            field=models.CharField(max_length=17, validators=[django.core.validators.RegexValidator(message='format: +998 XX XXX XX XX', regex='^\\+998 ?\\d{2} ?\\d{3} ?\\d{2} ?\\d{2}$')]),
        ),
    ]
