# Generated by Django 6.0.4 on 2026-09-15 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0017_order_recipient_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('paying', 'Toʻlanmoqda'), ('paid', 'Toʻlangan'), ('processing', 'Jarayonda'), ('on_the_way', 'Yetkazilmoqda'), ('done', 'Bajarildi'), ('cancelled', 'Bekor qilindi')], db_index=True, default='paying', max_length=50),
        ),
    ]
