# Generated by Django 6.0.4 on 2026-04-27 02:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0002_alter_cartitem_price_stat'),
        ('product', '0005_alter_variant_colour_alter_variant_size'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartitem',
            name='variant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cart_items', to='product.variant'),
        ),
    ]
